star = raw_input("Enter a object: ")
world = raw_input("Enter a Place: ")
diamond = raw_input("Enter a object: ")
sky = raw_input("Enter a Place: ")
sun = raw_input("Enter a object: ")
light = raw_input("Enter a descriptive word: ")
dark = raw_input("Enter a descriptive word: ")
tiny = raw_input("Enter a size: ")
he = raw_input("Enter a name: ")
blue = raw_input("Enter a color: ")
eye = raw_input("Enter a object: ")

print ("Twinkle, twinkle, little " + star +",")
print ("How I wonder where you are!")
print ("Up above the " + world + " so high,")
print ("Like a " + diamond + "in the " + sky + " .")

print ("When the blazing " + sun + "is gone,")
print ("When he nothing shines upon,")
print ("Then you show your little " + light + ",")
print ("Twinkle, twinkle, all the night.")

print ("Then the traveller in the " + dark + " ")
print ("Thanks you for your " + tiny + " sparks;")
print (" " + he + " could not see which way to go,")
print ("If you did not twinkle so.")

print ("In the " + dark + " " + blue + " sky you keep,")
print ("And often through my curtains peep,")
print ("For you never shut your " + eye + "")
print ("Till the " + sun + " is in the " + sky + ".")

print ("As your bright and " + tiny + " spark")
print ("Lights the traveller in the " + dark + ",")
print ("Though I know not what you are,")
print ("Twinkle, twinkle, little " + star + ".")
